export const incompatibleFonts = [
  "Allkin",
  "Chiron GoRound TC",
  "Chiron Sung HK",
  "Chiron Hei HK",
  "Linefont",
  "Material Icons",
  "Material Icons Outlined",
  "Material Icons Round",
  "Material Icons Sharp",
  "Material Icons Two Tone",
  "Material Symbols",
  "Material Symbols Rounded",
  "Material Symbols Outlined",
  "Material Symbols Sharp",
  "Playwrite AR",
  "Playwrite AR Guides",
  "Playwrite AT",
  "Playwrite AT Guides",
  "Playwrite AU NSW",
  "Playwrite AU SA",
  "Playwrite AU QLD",
  "Playwrite AU QLD Guides",
  "Playwrite AU NSW Guides",
  "Playwrite AU SA Guides",
  "Playwrite AU TAS",
  "Playwrite AU TAS Guides",
  "Playwrite AU VIC Guides",
  "Playwrite BE VLG",
  "Playwrite BE VLG Guides",
  "Playwrite BE WAL",
  "Playwrite BE WAL Guides",
  "Playwrite AU VIC",
  "Playwrite BR",
  "Playwrite CA",
  "Playwrite BR Guides",
  "Playwrite CA Guides",
  "Playwrite CL Guides",
  "Playwrite CL",
  "Playwrite CO",
  "Playwrite CO Guides",
  "Playwrite CU Guides",
  "Playwrite CU",
  "Playwrite CZ Guides",
  "Playwrite CZ",
  "Playwrite DE Grund",
  "Playwrite DE Grund Guides",
  "Playwrite DE LA",
  "Playwrite DE LA Guides",
  "Playwrite DE SAS",
  "Playwrite DE SAS Guides",
  "Playwrite DE VA Guides",
  "Playwrite DK Loopet",
  "Playwrite DE VA",
  "Playwrite DK Uloopet",
  "Playwrite DK Uloopet Guides",
  "Playwrite ES Deco Guides",
  "Playwrite ES Guides",
  "Playwrite ES",
  "Playwrite ES Deco",
  "Playwrite DK Loopet Guides",
  "Playwrite FR Moderne",
  "Playwrite FR Moderne Guides",
  "Playwrite FR Trad",
  "Playwrite GB J",
  "Playwrite FR Trad Guides",
  "Playwrite GB J Guides",
  "Playwrite GB S Guides",
  "Playwrite GB S",
  "Playwrite HR Guides",
  "Playwrite HR",
  "Playwrite HR Lijeva",
  "Playwrite HR Lijeva Guides",
  "Playwrite HU Guides",
  "Playwrite ID",
  "Playwrite HU",
  "Playwrite ID Guides",
  "Playwrite IE Guides",
  "Playwrite IE",
  "Playwrite IN",
  "Playwrite IN Guides",
  "Playwrite IS",
  "Playwrite IT Moderna",
  "Playwrite IS Guides",
  "Playwrite IT Moderna Guides",
  "Playwrite IT Trad",
  "Playwrite IT Trad Guides",
  "Playwrite MX",
  "Playwrite MX Guides",
  "Playwrite NG Modern",
  "Playwrite NL Guides",
  "Playwrite NL",
  "Playwrite NG Modern Guides",
  "Playwrite NO",
  "Playwrite NO Guides",
  "Playwrite NZ",
  "Playwrite NZ Basic",
  "Playwrite NZ Basic Guides",
  "Playwrite NZ Guides",
  "Playwrite PE Guides",
  "Playwrite PE",
  "Playwrite PL",
  "Playwrite PL Guides",
  "Playwrite PT",
  "Playwrite PT Guides",
  "Playwrite RO",
  "Playwrite SK",
  "Playwrite RO Guides",
  "Playwrite SK Guides",
  "Playwrite TZ",
  "Playwrite TZ Guides",
  "Playwrite US Modern",
  "Playwrite US Modern Guides",
  "Playwrite VN Guides",
  "Playwrite US Trad Guides",
  "Playwrite US Trad",
  "Playwrite VN",
  "Playwrite ZA",
  "Playwrite ZA Guides",
  "Wavefont"
];